<link type="text/css" rel="stylesheet" href="css/gtd.css" media="all">
<link type="text/css" rel="stylesheet" href="css/smoothness/jquery-ui-1.7.1.custom.css" media="all">
<script type="text/javascript" src="jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="jquery-ui-1.7.1.custom.min.js"></script>
<script type="text/javascript" src="jquery.scrollTo-min.js"></script>
<script type="text/javascript" src="timeline_2.3.0/timeline_js/timeline-api.js?bundle=true"></script>
<script type="text/javascript" src="gtd.js"></script>
